name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install libs
        run: forge install

      - name: Check formatting
        run: forge fmt --check

      # ✅ Build WITH build-info so Slither can parse artifacts
      - name: Build (with build-info for Slither)
        run: |
          forge clean
          forge build --build-info --build-info-path out/build-info

      - name: Slither (use Foundry artifacts + config)
        uses: crytic/slither-action@v0.4.1
        with:
          target: .
          ignore-compile: true
          slither-version: '0.11.3'
          solc-version: '0.8.24'
          fail-on: medium
          sarif: true
          slither-config: .slither.json
          slither-args: >-
            --config-file ./.slither.json
            --foundry-ignore-compile
            --foundry-out-directory out
            --exclude-dependencies
            --filter-paths "(^lib/|^test/|^script/)"

      - name: Gas snapshot
        run: |
          forge snapshot
          git diff --exit-code gas-snapshot || (echo "gas-snapshot changed; commit updated snapshot" && exit 1)

      - name: Coverage
        run: forge coverage --report lcov
