name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable
      - name: Cache libs
        run: forge install
      - name: Check formatting
        run: forge fmt --check
      - name: Build
        run: forge build
      - name: Placeholder scan
        run: |
          ! grep -RInE "TODO|FIXME|PLACEHOLDER" --exclude-dir=lib -- src test script README.md || (echo "Placeholders found" && exit 1)
      - name: Tests
        run: forge test -vvv
      - name: Slither
        uses: crytic/slither-action@v0.3.0
        with:
          node-version: 20
          target: .
          fail-on: medium
          slither-args: --exclude-informational
      - name: Gas snapshot
        run: |
          forge snapshot
          git diff --exit-code gas-snapshot || (echo "gas-snapshot changed; commit updated snapshot" && exit 1)
      - name: Coverage
        run: forge coverage --report lcov
